theme = "kanagawa"

[editor]
line-number = "relative"
color-modes = true 
end-of-line-diagnostics = "hint"
completion-timeout = 50

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
center = ["diagnostics"]
right = ["version-control", "selections", "position", "file-type"]

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true

[keys.normal.space]
"q" = ":buffer-close"

[keys.insert]
j = { k = "normal_mode" }
