# --- HYPRLAND AND ESSENTIALS ---
WINDOW_MANAGER=(
    niri-git
    ghostty
    hypridle
    matugen-bin
    wl-clipboard
    cliphist
    sunsetr-bin
    nwg-look
    xdg-desktop-portal-gnome
    xdg-desktop-portal-gtk
    gnome-keyring
    # archlinux-xdg-menu
    # xdg-user-dirs
    qtengine-git
    darkly-bin
)

BLUETOOTH=(
    bluez
    bluez-utils
    blueman                 # Bluetooth manage
)

WIFI=(
    nmgui-bin
)

# --- QUICK SHELL ---
QUICKSHELL=(
    quickshell-git
    qt6-5compat
    ttf-material-symbols-variable-git
    wf-recorder
    libqalculate
    tesseract
    tesseract-data-eng 
)

# --- FILE MANAGEMENT ---
FILE_MANAGEMENT=(
    nautilus
    gvfs
    gvfs-mtp
    udisks2
    sushi
    loupe
    gnome-disk-utility
)

# --- CORE UTILITIES ---
CORE_UTILS=(
    git
    stow
    brightnessctl
    power-profiles-daemon
    pacman-contrib
    wget
)

# --- CODECS ---
CODECS=(
    gst-plugins-base
    gst-plugins-good
    gst-plugins-bad
    gst-plugins-ugly
    gst-libav
)

# --- FONTS ---
FONTS=(
    ttf-jetbrains-mono-nerd
    noto-fonts
    noto-fonts-emoji
    ttf-rubik-vf
)

# --- AUDIO ---
AUDIO=(
    pipewire
    pipewire-alsa
    jack
    pipewire-pulse
    wireplumber
    pavucontrol
    easyeffects
    lsp-plugins-lv2
    calf
    playerctl
)
