# --- System Services to Enable ---
SERVICES=(
    udisks2.service         # Disk management/automounting
    bluetooth.service       # Bluetooth support
    paccache.timer          # Auto clean cache
)
