return {
	-- 	"nvim-treesitter/nvim-treesitter-textobjects",
	-- 	branch = "main", -- Важно!
	-- 	dependencies = { "nvim-treesitter/nvim-treesitter" },
	-- 	config = function()
	-- 		require("nvim-treesitter-textobjects").setup({
	-- 			select = {
	-- 				enable = true,
	-- 				lookahead = true, -- Автоматический прыжок вперед к объекту
	-- 				keymaps = {
	-- 					-- Используем стандартные буквы: f - function, c - class, a - parameter/argument
	-- 					["af"] = "@function.outer",
	-- 					["if"] = "@function.inner",
	-- 					["ac"] = "@class.outer",
	-- 					["ic"] = "@class.inner",
	-- 					["aa"] = "@parameter.outer", -- а - для аргументов/параметров
	-- 					["ia"] = "@parameter.inner",
	-- 				},
	-- 			},
	-- 			move = {
	-- 				enable = true,
	-- 				set_jumps = true, -- Сохранять прыжки в jumplist (Ctrl-o / Ctrl-i)
	-- 				goto_next_start = {
	-- 					["]m"] = "@function.outer",
	-- 					["]]"] = "@class.outer",
	-- 				},
	-- 				goto_next_end = {
	-- 					["]M"] = "@function.outer",
	-- 					["]["] = "@class.outer",
	-- 				},
	-- 				goto_previous_start = {
	-- 					["[m"] = "@function.outer",
	-- 					["[["] = "@class.outer",
	-- 				},
	-- 				goto_previous_end = {
	-- 					["[M"] = "@function.outer",
	-- 					["[]"] = "@class.outer",
	-- 				},
	-- 			},
	-- 			swap = {
	-- 				enable = true,
	-- 				swap_next = {
	-- 					["<leader>na"] = "@parameter.inner", -- n - next argument
	-- 				},
	-- 				swap_previous = {
	-- 					["<leader>pa"] = "@parameter.inner", -- p - previous argument
	-- 				},
	-- 			},
	-- 		})
	--
	-- 		-- Делаем перемещения повторяемыми с помощью ; и ,
	-- 		local ts_repeat_move = require("nvim-treesitter-textobjects.repeatable_move")
	-- 		vim.keymap.set({ "n", "x", "o" }, ";", ts_repeat_move.repeat_last_move_next)
	-- 		vim.keymap.set({ "n", "x", "o" }, ",", ts_repeat_move.repeat_last_move_previous)
	--
	-- 		-- Чтобы f, F, t, T тоже работали с ; и ,
	-- 		vim.keymap.set({ "n", "x", "o" }, "f", ts_repeat_move.builtin_f_expr, { expr = true })
	-- 		vim.keymap.set({ "n", "x", "o" }, "F", ts_repeat_move.builtin_F_expr, { expr = true })
	-- 		vim.keymap.set({ "n", "x", "o" }, "t", ts_repeat_move.builtin_t_expr, { expr = true })
	-- 		vim.keymap.set({ "n", "x", "o" }, "T", ts_repeat_move.builtin_T_expr, { expr = true })
	-- 	end,
}
