"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$fill\
$time\
$cmd_duration
$character\
"""

[git_branch]
style = "bright-black"
format = "[$branch]($style)"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"


[fill]
symbol = " "

[directory]
style = "bold blue"
truncation_length = 3
truncate_to_repo = false
format = " [$path]($style)[$read_only]($read_only_style) "

[character]
success_symbol = "[ ->](green)"
error_symbol = "[ ->](red)"
format = "$symbol "

[cmd_duration]
min_time = 1000
format = "took [$duration]($style) "
